language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: 
  - mkdir -p build/logs 
  - phpunit

after_script:
  - php vendor/bin/coveralls -v
